export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_ALL_PRODUCTS_PAGE = "GET_ALL_PRODUCTS_PAGE";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const GET_ERROR = "GET_ERROR";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const GET_BRAND = "GET_BRAND";

export const CREATE_USER = "CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const CREATE_REVIEW = "CREATE_REVIEW";
export const All_REVIEW_PRODUCT = "All_REVIEW_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const USER_WISHLIST = "USER_WISHLIST";
export const ADD_COUPON = "ADD_COUPON";
export const ALL_COUPON = "ALL_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const ONE_COUPON = "ONE_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const ALL_ADDRESS = "ALL_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const ONE_ADDRESS = "ONE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
