export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_ALL_PRODUCTS_PAGE = "GET_ALL_PRODUCTS_PAGE";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const GET_ERROR = "GET_ERROR";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const GET_BRAND = "GET_BRAND";
